### ISSUE TITLE
Add multiplicative noise?

### ISSUE THREAD

**Issue by sdwfrost** [SciML/StochasticDiffEq.jl#336]
In some cases e.g. where states are enforced to be positive, it makes sense for the noise to be multiplicative rather than additive. One option is to model log-transformed states, but it would be less unwieldy to be able to add e.g. gamma distributed noise as in [https://www.sciencedirect.com/science/article/pii/S0304414911001761](https://www.sciencedirect.com/science/article/pii/S0304414911001761).

**Comment by ChrisRackauckas** [comment]
Multiplicative noise is a form of diagonal noise, so it's not specifically specialized on in the solvers since things like SOSRI are a form of specialization on them. That said, this is a longer running thread. https://arxiv.org/abs/1804.04344 in section 4 shows how methods for additive noise can in theory be used, and that would be a nice optimization, but it's really really difficult to do this in a general sense inside of the solver. So instead we're looking at https://github.com/SciML/ModelingToolkit.jl/issues/140 . So I'm closing this as an issue that probably should be solved by ModelingToolkit, though there's a chance I revive the numerical transformation approach in the future.

**Comment by sdwfrost** [comment]
Thanks for the pointer to your paper; I'll take a look at the transform approach. Do you think that in the meantime an Euler scheme with multiplicative noise is OK, along the lines of [this](https://royalsocietypublishing.org/doi/10.1098/rsif.2009.0151#d3e3156)?

**Comment by ChrisRackauckas** [comment]
Yes, and the diagonal noise interface is very natural for multiplicative noise, i.e.:

https://docs.sciml.ai/latest/tutorials/sde_example/#Example-2:-Systems-of-SDEs-with-Diagonal-Noise-1

Here's changing that from additive to multiplicative noise:

```julia
function lorenz(du,u,p,t)
  du[1] = 10.0(u[2]-u[1])
  du[2] = u[1]*(28.0-u[3]) - u[2]
  du[3] = u[1]*u[2] - (8/3)*u[3]
end

function σ_lorenz(du,u,p,t)
  du[1] = 3.0u[1]
  du[2] = 3.0u[2]
  du[3] = 3.0u[3]
end

prob_sde_lorenz = SDEProblem(lorenz,σ_lorenz,[1.0,0.0,0.0],(0.0,10.0))
sol = solve(prob_sde_lorenz)
plot(sol,vars=(1,2,3))
```

FWIW, most of these routines were originally made for the case of multiplicative noise!

**Comment by sdwfrost** [comment]
Doesn't your example still have noise that is added to the ODE system? What I mean is a system where du = du*dW where dW is Gamma white noise (see `rgammawn` in [https://www.rdocumentation.org/packages/pomp/versions/1.19/topics/eulermultinom](https://www.rdocumentation.org/packages/pomp/versions/1.19/topics/eulermultinom))

**Comment by ChrisRackauckas** [comment]
the system is `x' = 10(y-x) + 3x dW`, `y' = x(28-z) - y + 3y dW`, `z' = xy - 8/3 z + 3z dW`
